# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Life, the Universe and Fishing
name                     : "phwl"
email:
repository               : "phwl/phwl.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
description: >- # this means to ignore newlines until "baseurl:"
  A diary of my adventures in computer engineering, academia and, of course,
  fishing.
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true
search_full_content: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-include-cache

author:
  name   : "phwl"
  avatar : "/assets/images/bio-photo.jpg"
  location         : "Sydney, Australia"
  bio    : "" # "Carbon-based lifeform."
  links:
    - label: "papers"
      url: "/assets/papers"
    - label: "talks"
      url: "/talks"
    - label: "students"
      url: "/students"
    - label: "writing resources"
      url: "/writing-resources"

footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-f"
      url: "https://facebook.com/pleong"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-f"
      url: "https://linkedin.com/in/philip-h-w-leong-949484"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/philip_leong"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/phwl"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: false
      related: true
      use_math: false
      wide: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      use_math: false
      wide: true

comments:
  provider: "disqus"
  disqus:
    shortname: "phwl-github-io"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

picture:
  markup: "picture"
  presets:
    default:
      ppi: [1, 1.5, 2.0]
      source_medium:
        media: "(min-width: 40em)"
        width: "600"
      source_default:
        width: "600"
